name: build-test-lint
run-name: ${{github.actor}} builds & check project
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
     
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
    
